name: awesome
on: [ push ]

jobs:
  job1:
    name: print-env
    runs-on: ubuntu-latest
    steps:
      - name: checkout-step
        uses: actions/checkout@v2
      - name: run env command
        run: env | sort
  job2:
    name: print-files
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: run ls command
        run: ls

